# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
