# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aqar', '0003_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
