# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aqar', '0004_notifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='pr_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(max_length=100)),
                ('p_section', models.CharField(max_length=100)),
                ('sellerRole', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('view', models.CharField(max_length=100)),
                ('rooms', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('Baths', models.IntegerField(default=0)),
                ('year_bulit', models.IntegerField(default=0)),
                ('finish_type', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.URLField(default=True)),
                ('phone', models.IntegerField(default=0)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Name', models.CharField(max_length=200)),
                ('detailes', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('facilities', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('exp_price', models.IntegerField()),
                ('p_email', models.CharField(max_length=500, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project_property',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('building', 'Building'), ('other', 'Other'), ('land', 'Land'), ('office', 'Office'), ('store', 'Store'), ('villa', 'Villa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('cairo', 'Greater Cairo'), ('alexandria', 'Alexandria'), ('Ain El Sokhna', 'Ain El Sokhna'), ('Hurghada / Red Sea', 'Hurghada / Red Sea'), ('Sharm el Sheikh', 'Sharm el Sheikh'), ('Dakahlia / Mansoura', 'Dakahlia / Mansoura'), ('Sharqia / Zagazig', 'Sharqia / Zagazig'), ('Gharbia / Tanta', 'Gharbia / Tanta'), ('Ismailia', 'Ismailia'), ('Dumiat', 'Dumiat'), ('Suez', 'Suez'), ('Beheira / Damanhur', 'Beheira / Damanhur'), ('Aswan', 'Aswan'), ('Luxor', 'Luxor'), ('Asyut', 'Asyut'), ('Monufia / Shebeen El-Kom', 'Monufia / Shebeen El-Kom'), ('Qina', 'Qina'), ('Sohag', 'Sohag'), ('Sinai / Arish', 'Sinai / Arish'), ('El Fayoum', 'El Fayoum'), ('Port Said', 'Port Said'), ('Kafr el-Sheikh', 'Kafr el-Sheikh'), ('Bani Suef', 'Bani Suef'), ('El minia', 'El minia'), ('New Valley', 'New Valley'), ('Qalyubia / Banha', 'Qalyubia / Banha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('for_sell', 'For Rell'), ('for_rent', 'For Rent')], max_length=100),
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='project_property',
        ),
        migrations.AddField(
            model_name='pr_property',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.proj'),
        ),
    ]
