# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0006_auto_20160401_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
