# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aqar', '0007_auto_20160402_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('propertyType', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
